#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""f100_readonly.py — Nikon F100 10-pin read-only client.

READ-ONLY BY DESIGN. Implements CQ / MQ / OQ / LQ only.
`NP`, `DP`, `EP`, unknown opcodes, command payloads, and any EEPROM write are
intentionally NOT implemented. The same allowlist is enforced at request
construction, the live request API, and immediately before serial write. See
the public draft's docs/SAFETY.md and do not weaken this boundary casually.

The upstream implementation completed a physical Mac/F100 read on 2026-09-13.
Its 5-roll, 117-frame payload matched both Windows reference applications.
This public derivative is verified offline; see docs/VALIDATION.md for scope.

Offline usage needs only Python 3. Install pyserial only for live commands.

Usage:
    python3 f100_readonly.py ports              # list candidate serial devices
    python3 f100_readonly.py id                 # show a newly attached cable's USB ID
    python3 f100_readonly.py tables --table-dir DIR  # validate all four TSVs
    python3 f100_readonly.py lq --fixture dump.hex   # decode a captured LQ payload offline
    python3 f100_readonly.py compare --reference expected.json --capture dump.hex

Live CQ/MQ/OQ syntax is generated by mac-connection/f100_orchestrator.py and
requires the exact session ID, plan, admission report, final gate, port, and
new capture directory. LQ keeps the additional --experimental-live gate.

The safety policy requires observing the reference application's LQ traffic
before this client sends LQ live — CQ/MQ/OQ are allowed once electrical
validation and a successful connection are confirmed, but LQ specifically
is gated behind that observed-traffic step. So `lq` refuses to transmit
unless `--experimental-live` is passed explicitly, and prints an
unverified-hardware warning when it does. Prefer `--fixture` (decode a
raw hex/binary capture offline) whenever possible.

Optional: place separately obtained lq_shutter_speed_table.tsv /
lq_aperture_table.tsv / lq_focal_length_table.tsv /
lq_ev_compensation_table.tsv next to this script to get physical-unit LQ
decoding instead of raw codes. These externally derived tables are NOT bundled
or hardcoded here on purpose. The TSVs are tab-separated with CSV-style
quoting (e.g. the shutter table's raw 0xFD row is quoted and doubled to
encode a trailing inch/seconds mark, displaying as 1.5 seconds), so they
are parsed with the `csv` module, not a naive `str.split("\t")`.

Offline LQ decoding defaults to capture-derived formulas when no table is present. Use `--table-policy strict`
to fail closed or `--table-policy raw` to explicitly accept raw-code fallback.
Run the `tables` command to validate filenames, headers, row widths, byte ranges,
hex/decimal agreement, and duplicate codes before decoding a capture.
"""

from __future__ import annotations

import argparse
import contextlib
import csv
import glob
import json
import math
import f100_numeric
import sys
import time
import warnings
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

from f100_capture_session import CaptureSession

try:
    import serial
except ImportError:
    serial = None

SERIAL_EXCEPTION_TYPES = (serial.SerialException,) if serial is not None else ()


STATUS_SUCCESS = 0x61
STATUS_OBSERVED_NON_SUCCESS = 0x79
PARITY_REFERENCE_SCHEMA = "f100-parity-reference/v1"
PARITY_REFERENCE_ROLES = {
    "nikon_photo_secretary_ii": "manufacturer_reference",
    "camera_companion": "independent_cross_check",
    "synthetic": "synthetic_golden",
}
PARITY_EVIDENCE_KINDS = frozenset(
    {"synthetic", "application_export", "wire_capture_transcription"}
)

# Observed in CameraCompanion.exe (0x631518 / 0x6318cc), not a documented
# Nikon spec. Photo Secretary uses a different (async, non-fixed-delay)
# pattern for the same "00 then command" shape. Treat both as implementation
# artifacts, not protocol requirements — see COLD_START_STATIC_ANALYSIS.md.
ATTENTION_WAIT_S = 0.03
READ_WAIT_S = 0.07
# Photo Secretary uses a 40-second application-layer CQ/LQ timeout.  This is
# not claimed as a Nikon protocol limit, so callers can override it.
DEFAULT_RESPONSE_TIMEOUT_S = 40.0
DEFAULT_LQ_MAX_RESPONSE_LENGTH = 0xFFFF
DEFAULT_POST_FRAME_QUIET_S = 0.25
POLL_READ_S = 0.2
WRITE_TIMEOUT_S = 2.0
SERIAL_CONFIG = {
    "baudrate": 9600,
    "bytesize": 8,
    "parity": "even",
    "stopbits": 2,
    "read_timeout_seconds": POLL_READ_S,
    "write_timeout_seconds": WRITE_TIMEOUT_S,
    "dtr": True, "rts": False,
    "modem_control_profile": "windows_mq_observed_dtr_on_rts_off",
}


def _open_serial_safely(serial_module, port: str):
    """Open using the DTR-on/RTS-off profile observed in Windows MQ tests.

    Set requested line states before open; OS/adapter open-time transitions
    remain platform dependent. exclusive=True retains the advisory POSIX lock.
    This profile is not a claim that DTR-on is necessary on every adapter.
    """
    ser = serial_module.Serial(
        port=None,
        baudrate=9600,
        bytesize=serial_module.EIGHTBITS,
        parity=serial_module.PARITY_EVEN,
        stopbits=serial_module.STOPBITS_TWO,
        timeout=POLL_READ_S,
        write_timeout=WRITE_TIMEOUT_S,
        exclusive=True,
    )
    try:
        ser.dtr = True
        ser.rts = False
        ser.port = port
        ser.open()
    except BaseException:
        try:
            ser.close()
        except BaseException:
            pass
        raise
    return ser

# Construction and live transmission are deliberately separate policies.
# LQ frame construction remains available for offline fixtures and decoding,
# while live LQ requires the module-private capability issued only by the
# explicit CLI --experimental-live path. Python cannot protect against a
# caller intentionally importing private internals, but this prevents normal
# library/API use from accidentally bypassing the live gate.
_READ_ONLY_FRAME_OPCODES = frozenset({"CQ", "MQ", "OQ", "LQ"})
_DEFAULT_LIVE_OPCODES = frozenset({"CQ", "MQ", "OQ"})
_READ_ONLY_LITERAL_FRAMES = {
    "CQ": b"CQ\x00\x00",
    "MQ": b"MQ\x00\x00",
    "OQ": b"OQ\x00\x00",
    "LQ": b"LQ\x00\x00",
}
_EXPERIMENTAL_LQ_LIVE_CAPABILITY = object()
_LIVE_TRANSPORT_AUTHORITY = object()
_VERIFIED_LIVE_BINDING_AUTHORITY = object()


class ProtocolError(ValueError):
    """The bytes do not form a valid observed F100 frame."""


class ObservedNonSuccessStatus(ProtocolError):
    """The camera returned 0x79, whose official Nikon meaning is unknown."""


@dataclass(frozen=True)
class _LiveTransportAuthorization:
    authority: object
    port: str
    capture_identity: int
    integration_session_id: str


@dataclass(frozen=True)
class _VerifiedLiveBinding:
    """Opaque result issued only after the shared P3 verifier succeeds."""

    authority: object
    integration: dict


def _issue_live_transport_authorization(
    *, port: str, capture: CaptureSession, verified_binding: _VerifiedLiveBinding
) -> _LiveTransportAuthorization:
    """Issue the private open capability after the CLI's P3 verification."""
    if type(port) is not str or not port:
        raise ProtocolError("live authorization requires an exact serial port")
    if (
        type(verified_binding) is not _VerifiedLiveBinding
        or verified_binding.authority is not _VERIFIED_LIVE_BINDING_AUTHORITY
        or type(verified_binding.integration) is not dict
    ):
        raise ProtocolError("live authorization requires a verified P3 binding")
    integration = verified_binding.integration
    if integration.get("candidate_live_blocked") is True:
        raise ProtocolError("Candidate live access blocked; create fresh evidence under the approved policy")
    if (integration.get("operation_scope") in ("record-settings", "erase-records") or
            integration.get("binding_schema") == "f100-reconnect-binding/0.1"):
        import f100_operation_scope as operations
        try:
            operations.validate_live_policy(integration)
        except ValueError as exc:
            raise ProtocolError(str(exc)) from exc
    if integration.get("verified_before_device_open") is not True:
        raise ProtocolError("live authorization was not verified before device open")
    if integration.get("serial_port") != port:
        raise ProtocolError("live authorization serial port mismatch")
    session_id = integration.get("session_id")
    if type(session_id) is not str or not session_id:
        raise ProtocolError("live authorization session ID is missing")
    if capture is None or capture.integration != integration:
        raise ProtocolError("live authorization is not bound to the capture session")
    return _LiveTransportAuthorization(
        authority=_LIVE_TRANSPORT_AUTHORITY,
        port=port,
        capture_identity=id(capture),
        integration_session_id=session_id,
    )


@dataclass(frozen=True)
class CameraResponse:
    status: int
    data: bytes
    raw: bytes

    def require_success(self) -> bytes:
        if self.status == STATUS_SUCCESS:
            return self.data
        if self.status == STATUS_OBSERVED_NON_SUCCESS:
            raise ObservedNonSuccessStatus(
                f"camera returned observed non-success status 0x{self.status:02x}"
            )
        raise ProtocolError(f"unobserved camera status 0x{self.status:02x}")


def encode_request(opcode: str, payload: bytes = b"") -> bytes:
    """Encode the opcode/length/payload portion (the separate attention
    0x00 byte is sent on its own, before this).

    This is intentionally not a generic Nikon command encoder. Only the four
    read-only opcodes represented by this client may be constructed, and all
    four requests are payloadless. LQ construction remains available offline;
    its *live transmission* is gated separately.
    """
    if type(opcode) is not str:
        raise ProtocolError("opcode must be exactly two ASCII characters")
    if type(payload) is not bytes:
        raise ProtocolError("payload must be exact built-in bytes")
    if opcode not in _READ_ONLY_FRAME_OPCODES:
        raise ProtocolError(f"opcode {opcode!r} is outside the read-only allowlist")
    if payload:
        raise ProtocolError(f"{opcode}: read-only requests must not contain a payload")
    return _READ_ONLY_LITERAL_FRAMES[opcode]


def _validate_live_request(
    opcode: str,
    payload: bytes = b"",
    *,
    live_capability: Optional[object] = None,
) -> None:
    """Fail closed before any live serial open or write is attempted."""
    # Reuse the construction boundary so unknown/write opcodes and payloads
    # cannot enter the live path through a future caller.
    encode_request(opcode, payload)
    if opcode in _DEFAULT_LIVE_OPCODES:
        return
    if (
        opcode == "LQ"
        and live_capability is _EXPERIMENTAL_LQ_LIVE_CAPABILITY
    ):
        return
    raise ProtocolError(
        "LQ live transmission requires the explicit experimental-live capability"
    )


def _validate_serial_write(
    data: bytes,
    *,
    role: str,
    opcode: str,
    live_capability: Optional[object] = None,
) -> None:
    """Validate the exact bytes at the last boundary before ``ser.write``."""
    if type(data) is not bytes or type(role) is not str or type(opcode) is not str:
        raise ProtocolError("serial write inputs must use exact built-in types")
    _validate_live_request(
        opcode, live_capability=live_capability
    )
    if role == "attention":
        if data != b"\x00":
            raise ProtocolError(f"{opcode}: invalid attention write")
        return
    if role == "command":
        expected = _READ_ONLY_LITERAL_FRAMES[opcode]
        if data != expected:
            raise ProtocolError(
                f"{opcode}: serial command bytes do not match the allowed payloadless frame"
            )
        return
    raise ProtocolError(f"{opcode}: unsupported serial write role {role!r}")


class ResponseDecoder:
    """Incrementally reconstruct responses split across arbitrary reads.

    Same design as the audited f100link/protocol.py ResponseDecoder
    (20/20 regression tests passing as of the 6th re-audit): conservative
    default length cap, explicit reset() after an error, and decoded
    frames are never lost behind a later error in the same feed().
    """

    def __init__(self, *, maximum_length: int = 512) -> None:
        if not (1 <= maximum_length <= 0xFFFF):
            raise ValueError("maximum_length must be between 1 and 65535")
        self.maximum_length = maximum_length
        self._buffer = bytearray()

    @property
    def buffered(self) -> bytes:
        return bytes(self._buffer)

    def reset(self) -> bytes:
        dropped, self._buffer = bytes(self._buffer), bytearray()
        return dropped

    def feed(self, data: bytes) -> list[CameraResponse]:
        self._buffer.extend(data)
        decoded: list[CameraResponse] = []
        while len(self._buffer) >= 2:
            length = int.from_bytes(self._buffer[:2], "big")
            if length < 1:
                if decoded:
                    return decoded
                raise ProtocolError("response length must include at least a status byte")
            if length > self.maximum_length:
                if decoded:
                    return decoded
                raise ProtocolError(
                    f"response length {length} exceeds configured maximum {self.maximum_length}"
                )
            frame_size = 2 + length
            if len(self._buffer) < frame_size:
                break
            raw = bytes(self._buffer[:frame_size])
            del self._buffer[:frame_size]
            decoded.append(CameraResponse(status=raw[2], data=raw[3:], raw=raw))
        return decoded


class F100Link:
    """One open/close cycle per request.

    This matches only the *Camera Companion*-observed transport shape
    (single open, `00` attention, fixed 30ms wait, command, read). Photo
    Secretary is NOT the same: static analysis shows it sends attention
    `00` as a separate queued no-reply/purge/10ms/close operation, then
    opens a *new* port for MQ. Do not claim this class matches both —
    it is `camera_companion_observed` transport only. See the corrective
    audit (docs/VALIDATION.md) §2 P1."""

    def __init__(
        self,
        port: str,
        *,
        verbose: bool = False,
        response_timeout: float = DEFAULT_RESPONSE_TIMEOUT_S,
        post_frame_quiet: float = DEFAULT_POST_FRAME_QUIET_S,
        capture: Optional[CaptureSession] = None,
        live_authorization: Optional[_LiveTransportAuthorization] = None,
    ):
        if not math.isfinite(response_timeout) or not (0 < response_timeout <= 3600):
            raise ValueError("response_timeout must be finite and from 0 through 3600")
        if not math.isfinite(post_frame_quiet) or not (0 <= post_frame_quiet <= 60):
            raise ValueError("post_frame_quiet must be finite and from 0 through 60")
        self.port = port
        self.verbose = verbose
        self.response_timeout = response_timeout
        self.post_frame_quiet = post_frame_quiet
        self.capture = capture
        self._live_authorization = live_authorization

    def _require_live_transport_authorization(self) -> None:
        authorization = self._live_authorization
        if type(authorization) is not _LiveTransportAuthorization:
            raise ProtocolError("live serial access requires the verified CLI P3 binding")
        if (
            authorization.authority is not _LIVE_TRANSPORT_AUTHORITY
            or authorization.port != self.port
            or self.capture is None
            or authorization.capture_identity != id(self.capture)
            or self.capture.integration.get("session_id")
            != authorization.integration_session_id
        ):
            raise ProtocolError("live serial authorization does not match this request")

    def _log(self, msg: str) -> None:
        if self.verbose:
            print(f"  [link] {msg}", file=sys.stderr)

    @contextlib.contextmanager
    def _open(self):
        self._require_live_transport_authorization()
        if serial is None:
            raise RuntimeError("pyserial not installed. Run: pip3 install pyserial")
        if self.capture is not None:
            self.capture.record(
                "serial_open_attempt", port=self.port, serial_config=SERIAL_CONFIG
            )
        try:
            ser = _open_serial_safely(serial, self.port)
        except BaseException as exc:
            if self.capture is not None:
                self.capture.record(
                    "serial_open_failure",
                    exception_type=type(exc).__name__,
                    message=str(exc),
                )
            raise
        try:
            if self.capture is not None:
                self.capture.record("serial_open_success", port=self.port)
            yield ser
        finally:
            try:
                ser.close()
            except BaseException as exc:
                if self.capture is not None:
                    self.capture.record(
                        "serial_close_failure",
                        exception_type=type(exc).__name__,
                        message=str(exc),
                    )
                raise
            else:
                if self.capture is not None:
                    self.capture.record("serial_close_success", port=self.port)

    def _write(
        self,
        ser,
        data: bytes,
        *,
        role: str,
        opcode: str,
        live_capability: Optional[object] = None,
    ) -> None:
        # This is the final, non-bypassable boundary inside this client. Keep
        # it before capture bookkeeping and immediately before ser.write().
        try:
            _validate_serial_write(
                data,
                role=role,
                opcode=opcode,
                live_capability=live_capability,
            )
        except ProtocolError as exc:
            self._record_tx_rejected(
                exc,
                role=role,
                opcode=opcode,
                requested_bytes=len(data) if type(data) is bytes else None,
            )
            raise
        call_id = None
        if self.capture is not None:
            call_id = self.capture.tx_attempt(data, role=role, opcode=opcode)
        try:
            transferred = ser.write(data)
        except BaseException as exc:
            if self.capture is not None and call_id is not None:
                self.capture.tx_exception(
                    call_id, exc, role=role, opcode=opcode
                )
            raise
        if transferred is None:
            transferred = 0
        if self.capture is not None and call_id is not None:
            self.capture.tx_result(
                call_id, data, int(transferred), role=role, opcode=opcode
            )
        if transferred != len(data):
            raise ProtocolError(
                f"{opcode}: short serial write ({transferred}/{len(data)} bytes)"
            )

    def _record_tx_rejected(
        self,
        exc: ProtocolError,
        *,
        role: object,
        opcode: object,
        requested_bytes: Optional[int],
    ) -> None:
        if self.capture is None:
            return
        try:
            self.capture.record(
                "tx_rejected",
                role=role if type(role) is str else "invalid-type",
                opcode=opcode if type(opcode) is str else "invalid-type",
                requested_bytes=requested_bytes,
                reason=str(exc),
            )
        except BaseException:
            # Rejection logging is evidence only.  It must never turn a rejected
            # request into an attempted serial open or write.
            pass

    def _read(self, ser, size: int, *, opcode: str) -> bytes:
        try:
            chunk = ser.read(size)
        except BaseException as exc:
            if self.capture is not None:
                self.capture.read_exception(exc, opcode=opcode)
            raise
        if chunk and self.capture is not None:
            self.capture.rx(bytes(chunk), opcode=opcode)
        return chunk

    def _read_single_response(
        self,
        ser,
        opcode: str,
        *,
        maximum_length: int = 512,
    ) -> CameraResponse:
        """Collect exactly one response frame without discarding trailing data.

        After the first complete frame, continue polling for a short, configurable
        quiet window.  A second complete frame or a partial trailing frame is an
        explicit protocol error until real hardware evidence defines a different
        multi-frame policy.
        """
        decoder = ResponseDecoder(maximum_length=maximum_length)
        overall_deadline = time.monotonic() + self.response_timeout
        quiet_deadline: Optional[float] = None
        responses: list[CameraResponse] = []

        while True:
            now = time.monotonic()
            active_deadline = overall_deadline
            if quiet_deadline is not None:
                active_deadline = min(active_deadline, quiet_deadline)
            if now >= active_deadline:
                break

            chunk = self._read(ser, 128, opcode=opcode)
            if not chunk:
                continue
            self._log(f"<- {chunk.hex(' ')}")
            decoded = decoder.feed(chunk)
            if decoded:
                responses.extend(decoded)
                quiet_deadline = time.monotonic() + self.post_frame_quiet

        if decoder.buffered:
            raise ProtocolError(
                f"{opcode}: trailing partial response ({decoder.buffered.hex(' ')})"
            )
        if not responses:
            raise ProtocolError(
                f"{opcode}: no response within {self.response_timeout:g}s"
            )
        if len(responses) != 1:
            raise ProtocolError(
                f"{opcode}: expected exactly one response frame, got {len(responses)}"
            )
        response = responses[0]
        if self.capture is not None:
            self.capture.record(
                "response_decoded",
                opcode=opcode,
                status=response.status,
                data_bytes=len(response.data),
                raw_hex=response.raw.hex(),
            )
        return response

    def request(
        self,
        opcode: str,
        payload: bytes = b"",
        *,
        expected_len: Optional[int] = None,
        max_response_length: Optional[int] = None,
        live_capability: Optional[object] = None,
    ) -> CameraResponse:
        try:
            _validate_live_request(
                opcode, payload, live_capability=live_capability
            )
            frame = encode_request(opcode, payload)
        except ProtocolError as exc:
            requested_bytes = None
            if type(opcode) is str and len(opcode) == 2 and type(payload) is bytes:
                requested_bytes = 4 + len(payload)
            self._record_tx_rejected(
                exc,
                role="request",
                opcode=opcode,
                requested_bytes=requested_bytes,
            )
            raise
        if max_response_length is None:
            max_response_length = DEFAULT_LQ_MAX_RESPONSE_LENGTH if opcode == "LQ" else 512
        ResponseDecoder(maximum_length=max_response_length)  # validate before serial I/O
        with self._open() as ser:
            self._log(f"open {self.port}")
            # Retry only a complete, empty 79 frame; never retry I/O failures,
            # timeouts, malformed/extra frames or other status values.
            for attempt in range(2):
                self._write(
                    ser,
                    b"\x00",
                    role="attention",
                    opcode=opcode,
                    live_capability=live_capability,
                )
                self._log("-> 00 (attention)")
                time.sleep(ATTENTION_WAIT_S)
                self._write(
                    ser,
                    frame,
                    role="command",
                    opcode=opcode,
                    live_capability=live_capability,
                )
                self._log(f"-> {frame.hex(' ')} ({opcode})")
                time.sleep(READ_WAIT_S)
    
                response = self._read_single_response(
                    ser, opcode, maximum_length=max_response_length
                )
                if response.status != STATUS_OBSERVED_NON_SUCCESS:
                    break
                if response.data:
                    raise ProtocolError("0x79 response must not contain a payload")
                if attempt == 0:
                    if self.capture is not None:
                        self.capture.record("status_79_retry", opcode=opcode, retry=1)
                    time.sleep(0.3)

        if (
            expected_len is not None
            and response.status == STATUS_SUCCESS
            and len(response.data) != expected_len
        ):
            self._log(
                f"warning: {opcode} data length {len(response.data)} != expected {expected_len}"
            )
        return response

    def request_lq_camera_companion_preflight(
        self,
        *,
        max_response_length: int = DEFAULT_LQ_MAX_RESPONSE_LENGTH,
        live_capability: Optional[object] = None,
    ) -> CameraResponse:
        """Read MQ and OQ before experimental LQ.

        Each request owns its one conditional 79 retry, avoiding nested retries.
        The reference apps and the CS15 experiment support conditional retry,
        not a fixed two-round exchange. LQ remains capability-gated.
        """
        _validate_live_request(
            "LQ", live_capability=live_capability
        )
        mq = self.request("MQ", expected_len=1)
        mq_data = mq.require_success()
        if len(mq_data) != 1:
            raise ProtocolError(f"MQ preflight data must be 1 byte, got {len(mq_data)}")
        time.sleep(0.1)

        oq = self.request("OQ", expected_len=2)
        oq_data = oq.require_success()
        if len(oq_data) != 2:
            raise ProtocolError(f"OQ preflight data must be 2 bytes, got {len(oq_data)}")
        oq_value = int.from_bytes(oq_data, "big")
        if oq_value:
            time.sleep(0.1)

        return self.request(
            "LQ", max_response_length=max_response_length,
            live_capability=live_capability,
        )


# ---- CQ: 4-byte Custom Settings block --------------------------------------

# The upstream research checked 22 custom settings across three camera states.
# This public decoder currently exposes only CSM01/CSM17; this is an
# implementation limit, not the full extent of the upstream observations.
# Preserve raw bytes until the remaining decoders are implemented.
CSM_BITS_CONFIRMED = {
    1: (1, 0, "Automatic film rewind at end of roll"),
    17: (3, 7, "LCD illuminator activated by any button"),
}


def decode_cq(data: bytes) -> dict:
    if len(data) != 4:
        raise ProtocolError(f"CQ block must be 4 bytes, got {len(data)}")
    result: dict = {"raw_hex": data.hex(" ")}
    for number, (byte_idx, bit_idx, note) in CSM_BITS_CONFIRMED.items():
        result[f"CSM{number:02d}"] = {
            "value": bool(data[byte_idx] & (1 << bit_idx)),
            "note": note,
        }
    result["_note"] = (
        "This decoder exposes only CSM01/CSM17. Upstream observations cover all 22 settings; "
        "the remaining decoders are not implemented here. See raw_hex."
    )
    return result


# ---- MQ: 1-byte shooting-data settings -------------------------------------

def decode_mq(data: bytes) -> dict:
    if len(data) != 1:
        raise ProtocolError(f"MQ must be 1 byte, got {len(data)}")
    byte = data[0]
    return {
        "raw_hex": f"{byte:02x}",
        "raw_bin": f"{byte:08b}",
        "memory_full_action": "delete_old_data" if (byte & 0x01) else "stop_shooting",
        "record_shooting_data": bool(byte & 0x02),
        "recording_mode": "detailed" if (byte & 0x08) else "simple",
        "_note": (
            "Bits 0, 1 and 3 were checked against observed camera settings. "
            "Other bits have unknown meanings and must be "
            "preserved on any future write path (not implemented here)."
        ),
    }


# ---- OQ: 2-byte status, meaning still unconfirmed --------------------------

def decode_oq(data: bytes) -> dict:
    if len(data) != 2:
        raise ProtocolError(f"OQ must be 2 bytes, got {len(data)}")
    value = int.from_bytes(data, "big")
    return {
        "raw_hex": data.hex(" "),
        "value_be16": value,
        "_note": "NOT the frame count (confirmed: 0 frames returned 5 in the audit pcap). Exact meaning unconfirmed.",
    }


# ---- LQ: film roll / frame data --------------------------------------------

# name -> real filename in evidence/static/camera_companion/ (LQ_VALUE_TABLES.md
# §1). Only "shutter" breaks the naive `lq_{name}_table.tsv` pattern.
_VALUE_TABLE_FILENAMES = {
    "shutter": "lq_shutter_speed_table.tsv",
    "aperture": "lq_aperture_table.tsv",
    "focal_length": "lq_focal_length_table.tsv",
    "ev": "lq_ev_compensation_table.tsv",
}


def _table_directory(directory: Optional[Path] = None) -> Path:
    return Path(directory) if directory is not None else Path(__file__).resolve().parent


def _handle_missing_table(path: Path, policy: str) -> None:
    message = f"value table missing: {path}"
    if policy == "strict":
        raise FileNotFoundError(message)
    if policy == "warn":
        warnings.warn(message, RuntimeWarning, stacklevel=3)
    elif policy != "raw":
        raise ValueError("table policy must be one of: raw, warn, strict")


def _handle_table_problem(message: str, policy: str) -> None:
    if policy == "strict":
        raise ProtocolError(message)
    if policy == "warn":
        warnings.warn(message, RuntimeWarning, stacklevel=3)


def _load_value_table(
    name: str,
    *,
    directory: Optional[Path] = None,
    missing_policy: str = "raw",
) -> Optional[dict[int, str]]:
    """Load an optional raw->display TSV copied from the audit archive's
    evidence/static/camera_companion/ directory. Deliberately NOT
    hardcoded in this script — see module docstring.

    Columns are `raw_hex\traw_decimal\tdisplay` with CSV-style quoting
    (e.g. shutter raw 0xFD's display column is quoted and doubled to
    encode a trailing inch/seconds mark, displaying as 1.5 seconds) — this
    must go through `csv.reader`, not a bare `str.split("\\t")`, or both
    the quoting and the intended display column get mangled."""
    try:
        filename = _VALUE_TABLE_FILENAMES[name]
    except KeyError as exc:
        raise ValueError(f"unknown value table name: {name}") from exc
    if missing_policy not in {"raw", "warn", "strict"}:
        raise ValueError("table policy must be one of: raw, warn, strict")
    path = _table_directory(directory) / filename
    if not path.exists():
        _handle_missing_table(path, missing_policy)
        return None
    table: dict[int, str] = {}
    with path.open(encoding="utf-8", newline="") as f:
        reader = csv.reader(f, delimiter="\t")
        header = next(reader, None)
        if header is None or header[:3] != ["raw_hex", "raw_decimal", "display"]:
            _handle_table_problem(f"invalid value-table header: {path}", missing_policy)
        for line_number, row in enumerate(reader, start=2):
            if len(row) < 3:
                _handle_table_problem(
                    f"{path}:{line_number}: fewer than 3 columns", missing_policy
                )
                continue
            try:
                raw = int(row[0], 0)
                decimal = int(row[1], 10)
            except ValueError:
                _handle_table_problem(
                    f"{path}:{line_number}: invalid numeric value", missing_policy
                )
                continue
            if not (0 <= raw <= 0xFF) or raw != decimal or raw in table:
                _handle_table_problem(
                    f"{path}:{line_number}: inconsistent or duplicate raw value",
                    missing_policy,
                )
                continue
            table[raw] = row[2]
    return table


def validate_value_tables(directory: Optional[Path] = None) -> dict:
    """Validate all four optional TSVs without opening a serial device."""
    base = _table_directory(directory)
    report: dict = {"directory": str(base), "tables": {}, "ok": True}

    for name, filename in _VALUE_TABLE_FILENAMES.items():
        path = base / filename
        item = {"file": filename, "present": path.is_file(), "rows": 0, "errors": []}
        report["tables"][name] = item
        if not path.is_file():
            item["errors"].append("missing")
            report["ok"] = False
            continue

        seen: set[int] = set()
        try:
            with path.open(encoding="utf-8", newline="") as f:
                reader = csv.reader(f, delimiter="\t")
                header = next(reader, None)
                if header is None or header[:3] != ["raw_hex", "raw_decimal", "display"]:
                    item["errors"].append("invalid header")
                for line_number, row in enumerate(reader, start=2):
                    if len(row) < 3:
                        item["errors"].append(f"line {line_number}: fewer than 3 columns")
                        continue
                    try:
                        raw = int(row[0], 0)
                        decimal = int(row[1], 10)
                    except ValueError:
                        item["errors"].append(f"line {line_number}: invalid numeric value")
                        continue
                    if not (0 <= raw <= 0xFF):
                        item["errors"].append(f"line {line_number}: raw value outside byte range")
                    if raw != decimal:
                        item["errors"].append(f"line {line_number}: hex/decimal mismatch")
                    if raw in seen:
                        item["errors"].append(f"line {line_number}: duplicate raw value 0x{raw:02x}")
                    seen.add(raw)
                    item["rows"] += 1
        except (OSError, UnicodeError, csv.Error) as exc:
            item["errors"].append(f"read error: {exc}")

        if item["errors"]:
            report["ok"] = False

    return report


def decode_lq(
    data: bytes,
    *,
    table_dir: Optional[Path] = None,
    table_policy: str = "formula",
) -> dict:
    if len(data) < 1:
        raise ProtocolError("LQ response empty")

    mode = data[0]
    if mode not in (0x00, 0x01):
        raise ProtocolError(f"unexpected LQ mode byte 0x{mode:02x} (expected 00 or 01)")
    detailed = mode == 0x01
    record_size = 13 if detailed else 5

    tables = {
        name: _load_value_table(
            name, directory=table_dir, missing_policy="raw" if table_policy == "formula" else table_policy
        )
        for name in _VALUE_TABLE_FILENAMES
    }

    sources = {}

    def lookup(table_name: str, raw: int) -> str:
        table = tables[table_name]
        if table is not None and raw in table:
            label, source = table[raw], "external_table"
        elif table_policy == "formula":
            label, source = f100_numeric.display(table_name, raw)
        else:
            label, source = f"0x{raw:02x}", "raw"
        sources.setdefault(table_name, {})[f"0x{raw:02x}"] = source
        return label

    rolls = []
    i = 1
    while i < len(data):
        if data[i] != 0xF3:
            raise ProtocolError(f"expected roll start 0xF3 at offset {i}, got 0x{data[i]:02x}")
        if i + 3 > len(data):
            raise ProtocolError("truncated roll header")
        roll_number = int.from_bytes(data[i + 1 : i + 3], "big")
        i += 3
        frames = []
        film_speed_code: Optional[int] = None
        while i < len(data):
            # The trailer is exactly one byte immediately before 0xFD (per
            # STATIC_ANALYSIS.md §7: "FD 앞의 1바이트는 롤 객체의 +0x04
            # 필드"). BUT 0xFD is also a *valid* shutter-speed raw code
            # (lq_shutter_speed_table.tsv: 0xFD -> 1.5") that can appear
            # as a normal record byte — so "next byte is 0xFD" alone is
            # not sufficient, or a record with that shutter value gets
            # misparsed as a truncated roll (corrective audit P0). Only
            # accept this as the real trailer when the FD is also at a
            # genuine roll boundary: either the last 2 bytes of the whole
            # buffer, or immediately followed by the next roll's F3.
            if (
                i + 1 < len(data)
                and data[i + 1] == 0xFD
                and (i + 2 == len(data) or data[i + 2] == 0xF3)
            ):
                film_speed_code = data[i]
                i += 2
                break
            if i + record_size > len(data):
                raise ProtocolError("truncated frame record")
            rec = data[i : i + record_size]
            frame = {
                "frame_number": rec[0],
                "shutter_speed_raw": f"0x{rec[1]:02x}",
                "shutter_speed": lookup("shutter", rec[1]),
                "aperture_raw": f"0x{rec[2]:02x}",
                "aperture": lookup("aperture", rec[2]),
                "focal_length_raw": f"0x{rec[3]:02x}",
                "focal_length": lookup("focal_length", rec[3]),
                "flash_flags_raw": f"0x{rec[4]:02x}",
                # Flash type is bits 1:0 only; bit 4 (multiple_exposure) and
                # other bits are independent/reserved and never affect this
                # label. Real-hardware evidence (Roll 47/48, 2026-09-19):
                # 0=off, 1=non_ttl, 3=ttl observed; 2 is reserved/unobserved.
                "flash_type": {0: "off", 1: "non_ttl", 3: "ttl"}.get(
                    rec[4] & 0b11, f"unknown(0x{rec[4] & 0b11:02x})"
                ),
                "multiple_exposure": bool(rec[4] & 0b10000),
            }
            if detailed:
                sync_bits = (rec[12] >> 4) & 0b111
                frame.update(
                    {
                        "lens_shortest_focal_raw": f"0x{rec[5]:02x}",
                        "lens_shortest_focal": lookup("focal_length", rec[5]),
                        "lens_longest_focal_raw": f"0x{rec[6]:02x}",
                        "lens_longest_focal": lookup("focal_length", rec[6]),
                        "max_aperture_short_raw": f"0x{rec[7]:02x}",
                        "max_aperture_short": lookup("aperture", rec[7]),
                        "max_aperture_long_raw": f"0x{rec[8]:02x}",
                        "max_aperture_long": lookup("aperture", rec[8]),
                        "manual_ev_diff_raw": f"0x{rec[9]:02x}",
                        "manual_ev_diff": lookup("ev", rec[9]),
                        "exposure_comp_raw": f"0x{rec[10]:02x}",
                        "exposure_comp": lookup("ev", rec[10]),
                        "flash_comp_raw": f"0x{rec[11]:02x}",
                        "flash_comp": lookup("ev", rec[11]),
                        "mode_flags_raw": f"0x{rec[12]:02x}",
                        "meter_mode": ["matrix", "spot", "center_weighted", "center_weighted"][
                            rec[12] & 0b11
                        ],
                        "exposure_mode": ["P", "S", "A", "M"][(rec[12] >> 2) & 0b11],
                        # Real-hardware evidence (Roll 47/48, 2026-09-19):
                        # 0=normal, 1=slow, 2=rear, 3=red_eye, 4=red_eye_slow
                        # observed. 5/6/7 remain unobserved with normal
                        # user operation and are left semantic unknown, not
                        # guessed. rec[12] bit 7 is not part of this field.
                        "flash_sync": {
                            0: "normal",
                            1: "slow",
                            2: "rear",
                            3: "red_eye",
                            4: "red_eye_slow",
                        }.get(sync_bits, f"unknown(0x{sync_bits:02x})"),
                    }
                )
            frames.append(frame)
            i += record_size
        if film_speed_code is None:
            raise ProtocolError("roll not terminated by trailer byte + 0xFD")
        rolls.append(
            {
                "roll_number": roll_number,
                "film_speed_raw": f"0x{film_speed_code:02x}",
                "film_speed": f100_numeric.display("iso", film_speed_code)[0],
                "film_speed_source": f100_numeric.display("iso", film_speed_code)[1],
                "frame_count": len(frames),
                "frames": frames,
            }
        )

    return {
        "mode": "detailed" if detailed else "simple",
        "roll_count": len(rolls),
        "rolls": rolls,
        "_value_tables": {
            "directory": str(_table_directory(table_dir)),
            "loaded": {name: table is not None for name, table in tables.items()},
            "policy": table_policy,
            "sources_by_code": sources,
        },
        "_note": "Capture-derived default decoding; estimates and unknown codes are identified in _value_tables.sources_by_code. Raw bytes are always preserved.",
    }


# ---- CLI --------------------------------------------------------------------

def find_ports() -> list[str]:
    patterns = [
        "/dev/cu.usbserial*",
        "/dev/cu.usbmodem*",
        "/dev/cu.*PL2303*",
        "/dev/cu.*Prolific*",
        "/dev/tty.usbserial*",
    ]
    found: set[str] = set()
    for pattern in patterns:
        found.update(glob.glob(pattern))
    return sorted(found)


def run_cable_identification(args: argparse.Namespace) -> dict:
    """Run the shared unverified-candidate identity workflow."""
    connection_dir = Path(__file__).resolve().parent.parent / "mac-connection"
    if str(connection_dir) not in sys.path:
        sys.path.insert(0, str(connection_dir))
    try:
        import f100_first_use_assistant as first_use
    except ImportError as exc:
        raise ValueError(
            "cable ID check requires the sibling mac-connection directory"
        ) from exc
    identify_args = argparse.Namespace(
        root=args.evidence_root,
        session_id=args.session_id,
        observe_seconds=args.observe_seconds,
    )
    return first_use.run_identification(identify_args)


def _read_lq_fixture(path: str) -> bytes:
    """Load a captured LQ payload for offline decoding. Accepts either a
    raw binary file, or a text file of whitespace-separated hex bytes
    (e.g. `00 F3 00 01 ...`, newlines and comments starting with `#`
    allowed) — this is deliberately lenient about capture formats since
    fixtures may come from a hex dump, a pcap byte extract, or manual
    transcription of a Camera Companion capture."""
    raw = Path(path).read_bytes()
    try:
        text = raw.decode("ascii")
    except UnicodeDecodeError:
        return raw
    tokens = []
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            tokens.extend(line.split())
    if tokens and all(len(t) == 2 and all(c in "0123456789abcdefABCDEF" for c in t) for t in tokens):
        return bytes(int(t, 16) for t in tokens)
    return raw


_MISSING = object()


def load_parity_reference(path: Path) -> dict:
    """Load and validate an offline semantic-parity reference.

    The source block records an evidence claim supplied by the file author. It
    is validated for internal consistency, but loading it does not authenticate
    the claimed application or promote synthetic data to hardware evidence.
    """
    try:
        document = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ProtocolError(f"cannot read parity reference {path}: {exc}") from exc

    if not isinstance(document, dict):
        raise ProtocolError("parity reference must be a JSON object")
    if document.get("schema") != PARITY_REFERENCE_SCHEMA:
        raise ProtocolError(
            f"parity reference schema must be {PARITY_REFERENCE_SCHEMA!r}"
        )

    source = document.get("source")
    if not isinstance(source, dict):
        raise ProtocolError("parity reference source must be an object")
    application = source.get("application")
    expected_role = PARITY_REFERENCE_ROLES.get(application)
    if expected_role is None:
        raise ProtocolError(
            "reference source application must be one of: "
            + ", ".join(PARITY_REFERENCE_ROLES)
        )
    if source.get("reference_role") != expected_role:
        raise ProtocolError(
            f"{application} must use reference_role {expected_role!r}"
        )
    evidence_kind = source.get("evidence_kind")
    if evidence_kind not in PARITY_EVIDENCE_KINDS:
        raise ProtocolError(
            "reference source evidence_kind must be one of: "
            + ", ".join(sorted(PARITY_EVIDENCE_KINDS))
        )
    hardware_validated = source.get("hardware_validated")
    if not isinstance(hardware_validated, bool):
        raise ProtocolError("reference source hardware_validated must be boolean")
    if application == "synthetic":
        if evidence_kind != "synthetic":
            raise ProtocolError("synthetic references must use evidence_kind 'synthetic'")
        if hardware_validated:
            raise ProtocolError("synthetic references cannot be hardware-validated")
    elif evidence_kind == "synthetic":
        raise ProtocolError("application references cannot use synthetic evidence_kind")

    if hardware_validated:
        provenance = source.get("provenance")
        if not isinstance(provenance, dict):
            raise ProtocolError(
                "hardware-validated application references require provenance"
            )
        for field in (
            "run_id",
            "application_version",
            "approval_scope",
            "camera_state",
        ):
            if not isinstance(provenance.get(field), str) or not provenance[field].strip():
                raise ProtocolError(
                    f"hardware provenance {field} must be a non-empty string"
                )
        captured_at = provenance.get("captured_at_utc")
        if not isinstance(captured_at, str):
            raise ProtocolError(
                "hardware provenance captured_at_utc must be an ISO-8601 string"
            )
        try:
            captured_datetime = datetime.fromisoformat(
                captured_at.replace("Z", "+00:00")
            )
        except ValueError as exc:
            raise ProtocolError(
                "hardware provenance captured_at_utc must be valid ISO-8601"
            ) from exc
        if (
            captured_datetime.tzinfo is None
            or captured_datetime.utcoffset() != timedelta(0)
        ):
            raise ProtocolError(
                "hardware provenance captured_at_utc must use UTC"
            )
        capture_hash = provenance.get("raw_capture_sha256")
        if not (
            isinstance(capture_hash, str)
            and len(capture_hash) == 64
            and all(character in "0123456789abcdef" for character in capture_hash)
        ):
            raise ProtocolError(
                "hardware provenance raw_capture_sha256 must be 64 lowercase hex characters"
            )
        capture_size = provenance.get("raw_capture_size_bytes")
        if (
            not isinstance(capture_size, int)
            or isinstance(capture_size, bool)
            or capture_size <= 0
        ):
            raise ProtocolError(
                "hardware provenance raw_capture_size_bytes must be a positive integer"
            )

    if not isinstance(document.get("expected"), dict):
        raise ProtocolError("parity reference expected must be an object")
    return document


def _json_path(parent: str, key) -> str:
    if isinstance(key, int):
        return f"{parent}[{key}]"
    return f"{parent}.{key}"


def _append_parity_comparisons(expected, actual, path: str, output: list[dict]) -> None:
    if expected is None:
        output.append(
            {
                "path": path,
                "status": "UNKNOWN",
                "reference": None,
                "actual": "<missing>" if actual is _MISSING else actual,
            }
        )
        return

    if isinstance(expected, dict):
        if not isinstance(actual, dict):
            output.append(
                {
                    "path": path,
                    "status": "DIFFER",
                    "reference": expected,
                    "actual": "<missing>" if actual is _MISSING else actual,
                }
            )
            return
        for key, value in expected.items():
            _append_parity_comparisons(
                value, actual.get(key, _MISSING), _json_path(path, key), output
            )
        return

    if isinstance(expected, list):
        if not isinstance(actual, list):
            output.append(
                {
                    "path": path,
                    "status": "DIFFER",
                    "reference": expected,
                    "actual": "<missing>" if actual is _MISSING else actual,
                }
            )
            return
        output.append(
            {
                "path": f"{path}.length",
                "status": "MATCH" if len(expected) == len(actual) else "DIFFER",
                "reference": len(expected),
                "actual": len(actual),
            }
        )
        for index, value in enumerate(expected):
            item = actual[index] if index < len(actual) else _MISSING
            _append_parity_comparisons(
                value, item, _json_path(path, index), output
            )
        return

    output.append(
        {
            "path": path,
            "status": "MATCH" if actual is not _MISSING and expected == actual else "DIFFER",
            "reference": expected,
            "actual": "<missing>" if actual is _MISSING else actual,
        }
    )


def compare_lq_reference(reference: dict, decoded: dict) -> dict:
    """Compare a decoded LQ result against the reference's asserted subset."""
    comparisons: list[dict] = []
    _append_parity_comparisons(reference["expected"], decoded, "$", comparisons)
    counts = {
        status.lower(): sum(item["status"] == status for item in comparisons)
        for status in ("MATCH", "DIFFER", "UNKNOWN")
    }
    overall = "DIFFER" if counts["differ"] else (
        "UNKNOWN" if counts["unknown"] else "MATCH"
    )
    source = dict(reference["source"])
    if source["application"] == "synthetic":
        claim_limit = (
            "Synthetic structural match only; this cannot establish parity with "
            "Nikon Photo Secretary II, a physical F100, or Nikon specifications."
        )
    elif not source["hardware_validated"]:
        claim_limit = (
            "Reference metadata is not hardware-validated; a match does not establish "
            "live F100 parity."
        )
    else:
        claim_limit = (
            "The reference file asserts hardware evidence. This tool compares supplied "
            "semantics only and does not authenticate provenance or hardware safety."
        )
    return {
        "schema": PARITY_REFERENCE_SCHEMA,
        "reference_source": source,
        "overall": overall,
        "summary": counts,
        "comparisons": comparisons,
        "_claim_limit": claim_limit,
    }


def _validate_cli_live_binding(args, port: str) -> _VerifiedLiveBinding:
    """Load the shared P3 verifier only after an offline command is excluded."""
    connection_dir = Path(__file__).resolve().parent.parent / "mac-connection"
    if str(connection_dir) not in sys.path:
        sys.path.insert(0, str(connection_dir))
    try:
        import f100_live_binding as live_binding
    except ImportError as exc:
        raise ValueError(
            "live commands require the full project mac-connection binding verifier"
        ) from exc
    integration = live_binding.validate_live_binding(
        orchestration_plan=args.orchestration_plan,
        admission_report=args.admission_report,
        forwarding_gate=args.utm_forwarding_gate,
        integration_session_id=args.integration_session_id,
        serial_port=port,
        expected_mode="mac-client",
        expected_command=args.command,
        max_age_seconds=args.max_binding_age_seconds,
    )
    return _VerifiedLiveBinding(
        authority=_VERIFIED_LIVE_BINDING_AUTHORITY,
        integration=dict(integration),
    )




def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Nikon F100 10-pin read-only client — "
            "CQ/MQ/OQ/LQ ONLY. "
            "NP/DP/EP are not implemented; see docs/SAFETY.md."
        )
    )
    parser.add_argument(
        "--port",
        help="Exact serial device, e.g. /dev/cu.usbserial-XXXX (required for live)",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Log raw bytes")
    parser.add_argument(
        "--capture-dir",
        type=Path,
        help="Required for every live serial command. Must name a new directory; "
        "writes JSONL, directional raw bytes, and a SHA-256 manifest.",
    )
    parser.add_argument("--integration-session-id")
    parser.add_argument("--orchestration-plan", type=Path)
    parser.add_argument("--admission-report", type=Path)
    parser.add_argument("--utm-forwarding-gate", type=Path)
    parser.add_argument(
        "--max-binding-age-seconds",
        type=float,
        default=900,
        help="Maximum age for the exact admission report and final gate (default 900).",
    )
    parser.add_argument(
        "--response-timeout",
        type=float,
        default=DEFAULT_RESPONSE_TIMEOUT_S,
        help="Overall response timeout in seconds. Default 40 follows Photo "
        "Secretary's application limit; it is not a confirmed Nikon limit.",
    )
    parser.add_argument(
        "--post-frame-quiet",
        type=float,
        default=DEFAULT_POST_FRAME_QUIET_S,
        help="Quiet window after the first frame used to detect trailing frames "
        "(default: 0.25 seconds).",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("ports", help="List candidate serial devices")
    if (Path(__file__).resolve().parent.parent / "mac-connection" / "f100_first_use_assistant.py").is_file():
        cable_id_parser = sub.add_parser(
            "cable-id",
            aliases=["id"],
            help="Inspect an unverified candidate against a sealed USB baseline",
        )
        cable_id_parser.add_argument(
            "--evidence-root",
            type=Path,
            default=Path("evidence"),
            help="Directory for the ID-check transcript and read-only snapshots",
        )
        cable_id_parser.add_argument("--session-id")
        cable_id_parser.add_argument("--observe-seconds", type=int, default=30)
    tables_parser = sub.add_parser(
        "tables", help="Validate all four optional LQ value-table TSV files"
    )
    tables_parser.add_argument(
        "--table-dir",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="Directory containing the four lq_*_table.tsv files",
    )
    sub.add_parser("cq", help="Read Custom Settings (4 bytes)")
    sub.add_parser("mq", help="Read shooting-data settings (1 byte)")
    sub.add_parser("oq", help="Read shooting-data status (2 bytes)")
    lq_parser = sub.add_parser(
        "lq",
        help="Decode shooting-data rolls (offline fixture by default)",
    )
    lq_parser.add_argument(
        "--fixture",
        help="Decode a captured LQ payload offline instead of transmitting "
        "(hex text, whitespace-separated, or a raw binary file)",
    )
    lq_parser.add_argument(
        "--experimental-live",
        action="store_true",
        help="Actually transmit LQ to the camera. docs/SAFETY.md requires "
        "observing Camera Companion's own LQ traffic first — this path is "
        "observed on one Mac/F100 configuration. Mutually exclusive with --fixture.",
    )
    lq_parser.add_argument(
        "--max-response-length",
        type=int,
        default=DEFAULT_LQ_MAX_RESPONSE_LENGTH,
        help="Length-field cap for live LQ; default 65535. The timeout is an "
        "independent response-timeout limit; configure it "
        "explicitly if a capture needs more.",
    )
    lq_parser.add_argument(
        "--table-dir",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="Directory containing the optional LQ value-table TSV files",
    )
    lq_parser.add_argument(
        "--table-policy",
        choices=("formula", "warn", "strict", "raw"),
        default="formula",
        help="Missing table behavior: formula (default), warn/raw fallback, or strict failure",
    )
    compare_parser = sub.add_parser(
        "compare",
        help="Compare an LQ capture with a semantic reference JSON (offline only)",
    )
    compare_parser.add_argument(
        "--reference",
        type=Path,
        required=True,
        help="Reference JSON using the f100-parity-reference/v1 schema",
    )
    compare_parser.add_argument(
        "--capture",
        required=True,
        help="Captured or synthetic LQ payload (hex text or raw binary)",
    )
    compare_parser.add_argument(
        "--table-dir",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="Directory containing optional user-supplied LQ value-table TSV files",
    )
    compare_parser.add_argument(
        "--table-policy",
        choices=("formula", "warn", "strict", "raw"),
        default="raw",
        help="Missing table behavior (default raw for reproducible fixtures)",
    )

    args = parser.parse_args()

    if not math.isfinite(args.response_timeout) or not (0 < args.response_timeout <= 3600):
        parser.error("--response-timeout must be finite and from 0 through 3600")
    if not math.isfinite(args.post_frame_quiet) or not (0 <= args.post_frame_quiet <= 60):
        parser.error("--post-frame-quiet must be finite and from 0 through 60")

    if args.command == "ports":
        ports = find_ports()
        if not ports:
            print("No candidate serial devices found.")
        for p in ports:
            print(p)
        return 0

    if args.command in {"cable-id", "id"}:
        if args.observe_seconds < 1 or args.observe_seconds > 300:
            parser.error("--observe-seconds must be from 1 through 300")
        try:
            run_cable_identification(args)
        except (OSError, TypeError, ValueError) as exc:
            if not getattr(exc, "stop_already_reported", False):
                print("STOP: " + str(exc), file=sys.stderr)
            return 2
        except (EOFError, KeyboardInterrupt):
            print(
                "STOP: operator input ended; no later action is authorized",
                file=sys.stderr,
            )
            return 2
        return 0

    if args.command == "tables":
        report = validate_value_tables(args.table_dir)
        print(json.dumps(report, indent=2, ensure_ascii=False))
        return 0 if report["ok"] else 2

    if args.command == "compare":
        try:
            reference = load_parity_reference(args.reference)
            data = _read_lq_fixture(args.capture)
            decoded = decode_lq(
                data,
                table_dir=args.table_dir,
                table_policy=args.table_policy,
            )
            report = compare_lq_reference(reference, decoded)
        except (OSError, ValueError, ProtocolError) as exc:
            print("Cannot compare offline files: " + str(exc) + "\nCheck the input files. No serial port was opened.", file=sys.stderr)
            return 2
        print(json.dumps(report, indent=2, ensure_ascii=False))
        return {"MATCH": 0, "DIFFER": 3, "UNKNOWN": 4}[report["overall"]]

    if args.command == "lq":
        if args.fixture and args.experimental_live:
            sys.exit("--fixture and --experimental-live are mutually exclusive.")
        if args.fixture:
            try:
                data = _read_lq_fixture(args.fixture)
                result = decode_lq(
                    data,
                    table_dir=args.table_dir,
                    table_policy=args.table_policy,
                )
            except (OSError, ValueError, ProtocolError) as exc:
                print("Cannot read shooting-data file: " + str(exc) + "\nCheck the file path and use a complete LQ fixture. No serial port was opened.", file=sys.stderr)
                return 2
            print(json.dumps(result, indent=2, ensure_ascii=False))
            return 0
        if not args.experimental_live:
            sys.exit(
                "Refusing to transmit LQ live by default.\n"
                "Use the guided launcher for connection setup, or supply the live "
                "options and matching evidence described in docs/SAFETY.md.\n"
                "  - Decode a capture offline:  f100_readonly.py lq --fixture <file>\n"
                "  - The developer CLI also requires explicit live opt-in:\n"
                "      f100_readonly.py lq --experimental-live"
            )
        print(
            "Experimental live read: validated on one Mac/F100/Prolific configuration.\n"
            "This uses the observed read-only preflight sequence of Camera\n"
            "Companion's LQ preflight (MQ -> OQ -> 00 -> LQ).",
            file=sys.stderr,
        )

    if args.capture_dir is None:
        parser.error(
            "--capture-dir is required for every live serial command; "
            "offline ports/tables/fixture commands remain capture-free"
        )

    port = args.port
    if not port:
        parser.error(
            "--port is required for every live command; P3 forbids live autodetection"
        )
    binding_arguments = (
        args.integration_session_id,
        args.orchestration_plan,
        args.admission_report,
        args.utm_forwarding_gate,
    )
    if not all(binding_arguments):
        parser.error(
            "live commands require --integration-session-id, --orchestration-plan, "
            "--admission-report, and --utm-forwarding-gate"
        )
    try:
        verified_binding = _validate_cli_live_binding(args, port)
    except (OSError, ValueError) as exc:
        parser.error("live evidence binding failed: " + str(exc))

    integration = dict(verified_binding.integration)

    if serial is None:
        sys.exit(
            "pyserial 3.5 is required only for live camera commands. "
            "Install the dependencies in mac-client/requirements-live.txt, or use the guided launcher."
        )

    try:
        capture = CaptureSession(
            args.capture_dir,
            port=port,
            command=args.command,
            serial_config=SERIAL_CONFIG,
            integration=integration,
        )
    except (OSError, ValueError) as exc:
        sys.exit(f"Capture setup error: {exc}")

    try:
        live_authorization = _issue_live_transport_authorization(
            port=port, capture=capture, verified_binding=verified_binding
        )
    except ProtocolError as exc:
        capture.finish("failure", str(exc))
        sys.exit(f"Live authorization error: {exc}")

    link = F100Link(
        port,
        verbose=args.verbose,
        response_timeout=args.response_timeout,
        post_frame_quiet=args.post_frame_quiet,
        capture=capture,
        live_authorization=live_authorization,
    )

    capture_outcome = "failure"
    capture_error: Optional[str] = None
    try:
        if args.command == "cq":
            data = link.request("CQ", expected_len=4).require_success()
            print(json.dumps(decode_cq(data), indent=2, ensure_ascii=False))
        elif args.command == "mq":
            data = link.request("MQ", expected_len=1).require_success()
            print(json.dumps(decode_mq(data), indent=2, ensure_ascii=False))
        elif args.command == "oq":
            data = link.request("OQ", expected_len=2).require_success()
            print(json.dumps(decode_oq(data), indent=2, ensure_ascii=False))
        elif args.command == "lq":
            data = link.request_lq_camera_companion_preflight(
                max_response_length=args.max_response_length,
                live_capability=_EXPERIMENTAL_LQ_LIVE_CAPABILITY,
            ).require_success()
            print(
                json.dumps(
                    decode_lq(
                        data,
                        table_dir=args.table_dir,
                        table_policy=args.table_policy,
                    ),
                    indent=2,
                    ensure_ascii=False,
                )
            )
        capture_outcome = "success"
    except KeyboardInterrupt:
        capture_outcome = "interrupted"
        capture_error = "Interrupted by user"
        raise SystemExit("Interrupted by user")
    except ObservedNonSuccessStatus as exc:
        capture_error = f"Camera returned non-success status (0x79): {exc}"
        raise SystemExit(capture_error)
    except ProtocolError as exc:
        capture_error = f"Protocol error: {exc}"
        raise SystemExit(capture_error)
    except SERIAL_EXCEPTION_TYPES as exc:
        capture_error = f"Serial error: {exc}"
        raise SystemExit(capture_error)
    except OSError as exc:
        capture_error = f"I/O error: {exc}"
        raise SystemExit(capture_error)
    finally:
        capture.finish(capture_outcome, capture_error)

    return 0


if __name__ == "__main__":
    # Hard safety guard: this file must never grow NP/DP/EP support without
    # going through docs/SAFETY.md review first. Do not remove this note.
    sys.exit(main())
